inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/**/*'
    - 'test/**/*'
    - 'bin/**/*'

Rails:
  Enabled: true

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

## `and return` の形式を利用できるようにするため。基本的には、&& と || を使う
Style/AndOr:
  Exclude:
    - '**/*controller.rb'

Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Max: 140
  Exclude:
    - '**/spec/**/*'
    - '**/config/**/*'

Metrics/ClassLength:
  CountComments: false
  Max: 250

Metrics/ModuleLength:
  CountComments: false
  Max: 250
  Exclude:
    - '**/spec/**/*'

Metrics/MethodLength:
  CountComments: false
  Max: 30

Metrics/BlockLength:
  CountComments: false
  Max: 50
  Exclude:
    - '**/spec/**/*'
    - '**/*.rake'
    - '**/factories/**/*'
    - '**/config/routes.rb'

Metrics/AbcSize:
 Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 6

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - '**/config/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - '**/spec/**/*'

Style/GuardClause:
  Enabled: false # need to switch to true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - '**/spec/**/*'

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Rails/FilePath:
  Exclude:
    - 'config/application.rb'
    - 'config/environments/development.rb'

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/application_helper.rb'