# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rspec:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: 2.7.2
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --path vendor/bundle
    - name: migration
      env:
        RAILS_ENV: test
        S3_BUCKET : teppan-dev
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rails db:create
        bundle exec rails db:migrate
    - name: run rspec
      env:
        HOST_URL : http://127.0.0.1
        EMAIL_DOMAIN : dev.teppan-neta.com
        S3_BUCKET : teppan-dev
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ssUGRzKlxYYTwYeepcnZwvm/bE2R8Xfflbh+gUDw        
        STRIPE_SECRET_KEY : sk_test_Imi0zvitzJre0cl8GLfquoPY002z8NpTI9
        YAHOOJP_ID : dj00aiZpPW9MODdyenk5aERIUiZzPWNvbnN1bWVyc2VjcmV0Jng9OWM-
        YAHOOJP_SECRET : 9PepTJ91P0UC1suRh4ny5ET0zRsufF8Z6S0oAEDw
      run: bundle exec rspec
